#!/usr/bin/env python3
"""Assemble the authored site and fresh main-branch API documentation."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MARKER = ".weaver-docs-site"


def roc_executable(command: str) -> str:
    candidate = shutil.which(command)
    if candidate is None:
        raise SystemExit(f"Could not find Roc executable {command!r}; use --roc or add roc to PATH")
    return candidate


def require_pinned_roc(roc: str) -> None:
    expected = (ROOT / ".roc-version").read_text(encoding="utf-8").strip()
    output = subprocess.run(
        [roc, "version"], cwd=ROOT, text=True, stdout=subprocess.PIPE, check=True
    ).stdout.strip()
    if expected not in output:
        raise SystemExit(f"Expected Roc {expected}, but {roc} reported: {output}")


def assemble(output: Path, roc: str, url_root: str) -> None:
    if output.exists():
        if not (output / MARKER).is_file():
            raise SystemExit(f"Refusing to replace {output}: it was not created by this script")
        shutil.rmtree(output)
    shutil.copytree(ROOT / "www", output)
    (output / MARKER).write_text("generated by scripts/build_docs_site.py\n", encoding="utf-8")
    environment = os.environ.copy()
    environment["ROC_DOCS_URL_ROOT"] = url_root.rstrip("/")
    command = [roc, "docs", "package/main.roc", f"--output={output / 'main'}"]
    print(f"+ {subprocess.list2cmdline(command)}", flush=True)
    subprocess.run(command, cwd=ROOT, env=environment, check=True)
    print(f"Assembled documentation site in {output}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path(os.environ.get("DOCS_OUTPUT", "pages-site")))
    parser.add_argument("--roc", default=os.environ.get("ROC", "roc"))
    parser.add_argument("--url-root", default=os.environ.get("ROC_DOCS_URL_ROOT", "/weaver/main"))
    args = parser.parse_args()
    roc = roc_executable(args.roc)
    require_pinned_roc(roc)
    output = args.output if args.output.is_absolute() else ROOT / args.output
    assemble(output.resolve(), roc, args.url_root)


if __name__ == "__main__":
    main()
