name: CI

on:
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: Git ref to test
        required: false
        type: string
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: package examples (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Install Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # 2.2.1
        with:
          version: 0.16.0
          use-cache: false

      - name: Install Roc
        uses: ./.github/actions/setup-roc

      - name: Run checks
        shell: python
        run: import runpy; runpy.run_path("scripts/test.py", run_name="__main__")
